apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tienda-comidas-backend-hpa
  namespace: tienda-comidas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tienda-comidas-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
