name: CI-CD Tienda Backend ECS

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Backend
      run: |
        cd backend
        docker build -t tienda-backend .

    - name: Tag imagen ECR
      run: |
        docker tag tienda-backend:latest \
        542081623405.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest

    - name: Push ECR
      run: |
        docker push \
        542081623405.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest

    - name: Actualizar ECS Fargate
      run: |
        aws ecs update-service \
        --cluster tienda-cluster \
        --service tienda-service \
        --force-new-deployment